export const tabElements = {
  buttons: document.querySelectorAll('.tab-button'),
  contents: document.querySelectorAll('.tab-content'),
}

export const firmwareElements = {
  connectAndInitBtn: document.getElementById('ConnectAndInit'),
  connectionStatus: document.getElementById('ConnectionStatus'),
  downloadLatestBtn: document.getElementById('DownloadLatest'),
  downloadNightlyBtn: document.getElementById('DownloadNightly'),
  downloadStatus: document.getElementById('DownloadStatus'),
  latestVersionElement: document.getElementById('LatestVersion'),
  nightlyVersionElement: document.getElementById('NightlyVersion'),
  fileInput: document.getElementById('FileInput'),
  selectedFile: document.getElementById('SelectedFile'),
  writeBtn: document.getElementById('WriteFirmeware'),
  verifyBtn: document.getElementById('VerifyFirmeware'),
  runBtn: document.getElementById('RunFirmeware'),
  progressContainer: document.getElementById('ProgressContainer'),
  progressFill: document.getElementById('ProgressFill'),
  progressText: document.getElementById('ProgressText'),
  operationStatus: document.getElementById('OperationStatus'),
  connectList: document.getElementById('ConnectedList'),
  logBox: document.getElementById('LogBox'),
}

export const configElements = {
  connectConfigBtn: document.getElementById('ConnectConfigDevice'),
  configConnectList: document.getElementById('ConfigConnectedList'),
  configConnectionStatus: document.getElementById('ConfigConnectionStatus'),
  resetLeverBtn: document.getElementById('ResetLeverBtn'),
  readLeverInfoBtn: document.getElementById('ReadLeverInfoBtn'),
  readInputModeBtn: document.getElementById('ReadInputModeBtn'),
  setInputModeBtn: document.getElementById('SetInputModeBtn'),
  inputModeSelect: document.getElementById('InputModeSelect'),
  toggleMonitorBtn: document.getElementById('ToggleMonitorBtn'),
  lightTestBtn: document.getElementById('LightTestBtn'),
  saveConfigBtn: document.getElementById('SaveConfigBtn'),
  cancelConfigBtn: document.getElementById('CancelConfigBtn'),
  configOperationStatus: document.getElementById('ConfigOperationStatus'),
  deviceStat: document.getElementById('DeviceStatus'),
  configLogBox: document.getElementById('ConfigLogBox'),
}

export const inputTestElements = {
  connectInputTestBtn: document.getElementById('ConnectInputTestDevice'),
  inputTestConnectList: document.getElementById('InputTestConnectedList'),
  inputTestConnectionStatus: document.getElementById('InputTestConnectionStatus'),
  startInputTestBtn: document.getElementById('StartInputTestBtn'),
  stopInputTestBtn: document.getElementById('StopInputTestBtn'),
  inputTestStatus: document.getElementById('InputTestStatus'),
  joystickDot: document.getElementById('JoystickDot'),
  joystickX: document.getElementById('JoystickX'),
  joystickY: document.getElementById('JoystickY'),
  joystickRaw: document.getElementById('JoystickRaw'),
  rawInputStatus: document.getElementById('RawInputStatus'),
  rawButtons: document.getElementById('RawButtons'),
  inputTestLogBox: document.getElementById('InputTestLogBox'),
  arcadeButtons: {
    LA: document.getElementById('btn-LA'),
    LB: document.getElementById('btn-LB'),
    LC: document.getElementById('btn-LC'),
    RA: document.getElementById('btn-RA'),
    RB: document.getElementById('btn-RB'),
    RC: document.getElementById('btn-RC'),
    LSIDE: document.getElementById('btn-LSide'),
    RSIDE: document.getElementById('btn-RSide'),
    LMENU: document.getElementById('btn-LMenu'),
    RMENU: document.getElementById('btn-RMenu'),
    TEST: document.getElementById('btn-Test'),
    SERVICE: document.getElementById('btn-Service'),
  },
  coin1Condition: document.getElementById('Coin1Condition'),
  coin1Count: document.getElementById('Coin1Count'),
  coin2Condition: document.getElementById('Coin2Condition'),
  coin2Count: document.getElementById('Coin2Count'),
}

export const allButtons = [
  firmwareElements.connectAndInitBtn,
  firmwareElements.downloadLatestBtn,
  firmwareElements.downloadNightlyBtn,
  firmwareElements.writeBtn,
  firmwareElements.verifyBtn,
  firmwareElements.runBtn,
  configElements.connectConfigBtn,
  configElements.resetLeverBtn,
  configElements.readLeverInfoBtn,
  configElements.readInputModeBtn,
  configElements.setInputModeBtn,
  configElements.toggleMonitorBtn,
  configElements.lightTestBtn,
  configElements.saveConfigBtn,
  configElements.cancelConfigBtn,
  inputTestElements.connectInputTestBtn,
  inputTestElements.startInputTestBtn,
  inputTestElements.stopInputTestBtn,
]
