name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Verify package files
      run: |
        echo "package.json content:"
        cat package.json
        echo "package-lock.json exists:"
        ls -la package-lock.json
        
    - name: Install dependencies
      run: |
        # Use npm ci for faster, reliable, reproducible builds
        # Fall back to npm install if package-lock.json is out of sync
        npm ci || npm install
      
    - name: Build project
      run: npm run build
      
    - name: Prepare deployment files
      run: |
        # Copy all files from public to dist
        cp -r public/* dist/
        # List files to verify
        echo "Files in dist directory:"
        ls -la dist/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
